config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
 
  root 'home#index'

  get 'livestream/index'
  get 'livestream/show'
  get 'livestream/new'
  get 'livestream/update'
  get 'livestream/create'
  get 'livestream/destroy'

  get 'dashboard/index'
  get 'search_police', to: 'police#index'

  resources :livestream, only: [:index, :show, :new, :update, :create, :destroy]
  resources :police, only: [:index, :show, :new, :update, :create, :destroy] do
    get :search
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/police.rb
class Police < ApplicationRecord
  validates :name, presence: true
  validates :badge_number, presence: true
  validates :date_hired, presence: true



  def self.search(police)

    police = Police.where("name LIKE ? or badge_number LIKE ?",  
    "%#{params[:search]}%", "%#{params[:search]}%" ) 
    if params[:search].present?
    police
      end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_one_attached :image
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/livestream_controller.rb
class LivestreamController < ApplicationController
    include ActionController::Live
    # generate live video from devise camera


    def index
        
    end

    def new

    end

    def create

    end

    def edit

    end

end

app/controllers/police_controller.rb
class PoliceController < ApplicationController

    def show 
        
        @police = Police.find(params[:id])
    end

    def index

        @police = Police.paginate(page: params[:page], per_page: 10)
    end

    def search
        if params[:search].blank?  
          @police = Police.all  
        else  
          @police = Police.search(params)
        end  
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/livestream_helper.rb
module LivestreamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class=jumbotron text-center text-yellow>
      <h1 class="display-4">BadgeWatch</h1>
      <%= image_tag ("badge_watch.png") %>
      <h3>Get Started</h3>
      <p><small>Sign up for a new account, enter your email & get started.</small></p>
      <ul>
        <li>
          <% if current_user %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Sign in', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'Police Lookup', police_index_path %>
        </li>
      </ul>
    <% end %>
    </div>
  </div>
</div>


<footer id="sticky-footer" class="py-4 text-white">
  <div class="container text-center">
    <small>Copyright &copy;
    <%= link_to "Code for South Florida", 
    "https://codeforsouth.com/", class: "text-white" %>
    </small>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
  <nav class="navbar  sticky-top navbar-expand-lg navbar-light bg-light">
    <%= link_to "BadgeWatch", root_path, class: "navbar_brand", id: "logo" %>  
    <%= link_to image_tag("badge_watch.png", alt: "brand"), root_path, class: "logo-img" %>  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto navbar-center">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link", class: "sr-only" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to "Police Incidents", police_index_path %></a>
      </li>
    </ul>

    <div class="search" name="query">
    <%= form_tag search_police_path, method: :get do %>
      <div class="form-group row">
        <div class="col-sm-9 no-right-padding">
          <%= text_field_tag :search, params[:search], placeholder: "Police Database Lookup", 
          autofocus: "true", class: "form-control form-control-lg" %> 
        </div>
        <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, :name => nil, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</nav>
    
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BadgeWatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
  </head>

  <body class="image">
    <div class="container">  
    <%= render 'layouts/navigation' %>
    <%= yield %>
    </div>
  </body> 
</html>

app/views/livestream/index.html.erb
<h1>Live Stream</h1>

<%= react_component 'Streaming' %>
</br>
<p><button id="btn btn-success"><%= link_to "Home", home_index_path %></button>
<button><%= link_to "New Video", livestream_new_path %></button>
<button><%= link_to "Police Incidents", police_index_path %></button></p>

<form>
  <label for="img">Select image:</label>
  <input type="file" id="img" name="img" accept="image/*">
  <input type="submit">
</form>
<div>
<div class="player">

    <video id="vid" autoplay controls width="100%"" height="auto">></video>
    
          
        <script>
        navigator.mediaDevices.getUserMedia({
            video: true
        })
        .then(stream => {
            document.getElementById("vid").srcObject = stream;
        })
        </script>
        
</div>
<div>
  <script>
  var x = document.getElementById("demo");
function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
  x.innerHTML = "Latitude: " + position.coords.latitude +
  "<br>Longitude: " + position.coords.longitude;
}

function myMap() {
var mapProp= {
  center:new google.maps.LatLng(51.508742,-0.120850),
  zoom:5,
};
var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
}
  </script>
</div>

app/views/livestream/new.html.erb
<div>
  <p>Incident Details<%= text_area_tag(:message, "", size: "24x6") %><p>
</div>
<div>
  <p>Date <%= Date.today.to_datetime %></p>
</div>
<div>
  <p> Email (optional)<%= email_field(:user, :address) %>
</div>
<div>
  <p>Date of Incident<%= date_field(:task, :started_at) %></p>
<div>

app/views/livestream/show.html.erb
<h1>Upload Photo or Video</h1>

<div id="container">

<input type="file" name="file" onchange="selectedVideo(this);"/>
<video autoplay id="video" controls>
  <source id="source" type="video/mp4">
</video>
<script>
function selectedVideo(self) {
  var file = self.files[0]
  var reader = new FileReader()

  reader.onload = function(e)
    var source = e.target.result
    var video = document.getElementById("video")
    var src = document.getElementById("source")
    
    source.setAttribute("src", src)
    video.play()
    video.load()
};

window.addEventListener('load', function(){
  if(this.files && this.files[0]){
      document.querySelector(input[type="file"]).addEventListener('change', function())

        var img = document.getElementById("img")

        img.src = URL.createObjectURL(this.files[0])

        img.onload = imgLoaded

  }
})

function imgLoaded(e) {alert(e)}
<input type="file"/>
</script>

    <div>
    <p>Incident Details<%= text_area_tag(:message, "", size: "24x6") %><p>
    </div>
    <div>
    <p>Date <%= Date.today.to_datetime %></p>
    </div>
    <div>
    <p> Email (optional)<%= email_field(:user, :address) %>
    </div>
    <div>
    <p>Date of Incident<%= date_field(:task, :started_at) %></p>
<div>

</div>

app/views/police/index.html.erb
<h1>Officer Incident Database</h1> 
<div class="apple_pagination">
    <%= will_paginate @polce, :container => false %>
  </div>
<div>
  <table class="font-size table table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">Name: </th>
        <th scope="col">Badge Number: </th>
        <th scope="col">Date Hired: </th>
        <th class="padding-for-col col">Number of Administrative Complaints</th>
        <th scope="col">Number of Citizen Complaints</th>
        <th scope="col">Use of Force Incidents</th>
        <th scope="col">Complaint File</th>
      </tr>
    </theadd>
    <tbody>
      <% @police.each do |police| %>
      <tr scope="row">
      
        <td><%= link_to police.name, police_path(police) %></td>
        <td> <%= police.badge_number %> </td>
        <td> <%= police.date_hired %> </td>
        <td class="padding-for-col">  <%= police.num_of_admin_complaints %> </td>
        <td> <%= police.num_of_citizen_complaints %> </td>
        <td> <%= police.use_of_force_incidents %> </td>
        <td> <%= link_to police.complaint_link, target: '_blank' %> </td>
        
      </tr>
      <% end %>
    </tbody>
  </table>
  <button><%= link_to "Home", home_index_path %></button>
  
  <div class="apple_pagination">
    <%= will_paginate @polce, :container => false %>
  </div>
</div>

app/views/police/search.html.erb
<h1>Officer Details<h1>
<div class="card text-center">
  <div class="card-header">
  <%= police.each do |police| %>
    <p>Name: <%= @police.name %></p>
  <div class="card-body">  
    <p>Badge Number: <%= @police.badge_number %></p>
    <p>Date Hired: <%= @police.date_hired %></p>
    <p>Number of Administrative Complaints: <%= @police.num_of_admin_complaints %></p>
    <p>Number of Citizens Complaints: <%= @police.num_of_citizen_complaints %></p>
    <p>Number of Use of Force Incidents <%= @police.use_of_force_incidents %> </p>
    <p>Police Complaint File <%= @police.complaint_link %></p>
  </div> 
  </div>
</div>
<button btn btn-success>Back<% link_to police_index_path %></button> 

app/views/police/show.html.erb
<h1>Officer Details<h1>
<div class="card text-center">
  <div class="card-header">
    <p>Name: <%= @police.name %></p>
  <div class="card-body">  
    <p>Badge Number: <%= @police.badge_number %></p>
    <p>Date Hired: <%= @police.date_hired %></p>
    <p>Number of Administrative Complaints: <%= @police.num_of_admin_complaints %></p>
    <p>Number of Citizens Complaints: <%= @police.num_of_citizen_complaints %></p>
    <p>Number of Use of Force Incidents <%= @police.use_of_force_incidents %> </p>
    <p>Police Complaint File <%= @police.complaint_link %></p>
  </div> 
  </div>
</div>
</br>
<p><button id="btn btn-success"><%= link_to "Home", home_index_path %></button>
<button><%= link_to "Police Incidents", police_index_path, target: '_blank' %></button></p>